import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MainNav from './MainNav'
import Hero from './Hero'
import About from './About'
import TradingCards from './TradingCards'
import Guilds from './Guilds'
import Terrain from './Terrain'
import RoadMap from './RoadMap'

const Home: NextPage = () => {
	return (
		<div className="container">
			<Head>
				<title>The House NFT | Skribbs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainNav></MainNav>
			<Hero />
			<About />
			<RoadMap />
			<TradingCards />
			<img className="divider" src="/assets/divider.svg" />
			<Guilds />
			<img className="divider" src="/assets/divider.svg" />
			<Terrain />

			<div className="hero-footer">
				<h1 className="hero-text">
					Fine Art,
					<span>Cultural Exploration,</span>
					Technological Innovation.
				</h1>

				<div className="actions">
					<a className="button" href="#">
						<img className="icon" src="/assets/icon.svg" />
						<span>Read Whitepaper</span>
					</a>
					<a className="button" href="#">
						<img className="icon" src="/assets/discord.svg" />
						<span>Join Discord</span>
					</a>
					<a className="button" href="#">
						<img className="icon" src="/assets/twitter.svg" />
						<span>Follow Twitter</span>
					</a>
				</div>
			</div>

			<footer className="footer">
				<a href="https://skribbs.com" target="_blank" rel="noopener noreferrer">
					Powered by{' '}
					<Image
						src="/assets/skribbs.svg"
						alt="Skribbs Logo"
						width={100}
						height={24}
					/>
				</a>
			</footer>
		</div>
	)
}

export default Home
