import type { NextPage } from 'next'
import Head from 'next/head'

import MainNav from './sections/MainNav'
import Hero from './sections/Hero'
import About from './sections/About'
import TradingCards from './sections/TradingCards'
import Guilds from './sections/Guilds'
import Terrain from './sections/Terrain'
import RoadMap from './sections/RoadMap'
import Footer from './sections/Footer'


const Home: NextPage = () => {
	return (
		<div className="container">
			<Head>
				<title>The House NFT | Skribbs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainNav></MainNav>
			<Hero />
			<About />
			<RoadMap />
			<TradingCards />
			<img className="divider" src="/assets/extras/divider.svg" />
			<Guilds />
			<img className="divider" src="/assets/extras/divider.svg" />
			<Terrain />
			<Footer />
		</div>
	)
}

export default Home
